using System;
using System.Collections.Generic;
using System.Globalization;

namespace DocxToPdf
{
    public class LangScriptTag
    {
        private class LangScriptTagStruct
        {
            public String Name;
            public int LCID;
            public String ScriptTag;

            public LangScriptTagStruct(String name, int lcid, String scriptTag)
            {
                this.Name = name;
                this.LCID = lcid;
                this.ScriptTag = scriptTag;
            }
        }

        // http://blogs.msdn.com/b/officeinteroperability/archive/2013/04/22/office-open-xml-themes-schemes-and-fonts.aspx
        private static Dictionary<int, LangScriptTagStruct> LangScriptTags = new Dictionary<int, LangScriptTagStruct>()
        {
            {0x409, new LangScriptTagStruct("lidAmerican", 0x409, "Latn")},
            {0xc09, new LangScriptTagStruct("lidAustralian", 0xc09, "Latn")},
            {0x809, new LangScriptTagStruct("lidBritish", 0x809, "Latn")},
            {0x1009, new LangScriptTagStruct("lidEnglishCanadian", 0x1009, "Latn")},
            {0x403, new LangScriptTagStruct("lidCatalan", 0x403, "Latn")},
            {0x406, new LangScriptTagStruct("lidDanish", 0x406, "Latn")},
            {0x413, new LangScriptTagStruct("lidDutch", 0x413, "Latn")},
            {0x813, new LangScriptTagStruct("lidDutchBelgian", 0x813, "Latn")},
            {0x479, new LangScriptTagStruct("lidPapiamentu", 0x479, "Latn")},
            {0x40b, new LangScriptTagStruct("lidFinnish", 0x40b, "Latn")},
            {0x40c, new LangScriptTagStruct("lidFrench", 0x40c, "Latn")},
            {0xc0c, new LangScriptTagStruct("lidFrenchCanadian", 0xc0c, "Latn")},
            {0x407, new LangScriptTagStruct("lidGerman", 0x407, "Latn")},
            {0x807, new LangScriptTagStruct("lidSwissGerman", 0x807, "Latn")},
            {0xc07, new LangScriptTagStruct("lidAustrianGerman", 0xc07, "Latn")},
            {0x1007, new LangScriptTagStruct("lidGermanLuxembourg", 0x1007, "Latn")},
            {0x1407, new LangScriptTagStruct("lidGermanLiechtenstein", 0x1407, "Latn")},
            {0x410, new LangScriptTagStruct("lidItalian", 0x410, "Latn")},
            {0x414, new LangScriptTagStruct("lidNorskBokmal", 0x414, "Latn")},
            {0x814, new LangScriptTagStruct("lidNorskNynorsk", 0x814, "Latn")},
            {0x416, new LangScriptTagStruct("lidPortBrazil", 0x416, "Latn")},
            {0x816, new LangScriptTagStruct("lidPortIberian", 0x816, "Latn")},
            {0x40a, new LangScriptTagStruct("lidSpanish", 0x40a, "Latn")},
            {0x41d, new LangScriptTagStruct("lidSwedish", 0x41d, "Latn")},
            {0x419, new LangScriptTagStruct("lidRussian", 0x419, "Cyrl")},
            {0x405, new LangScriptTagStruct("lidCzech", 0x405, "Latn")},
            {0x40e, new LangScriptTagStruct("lidHungarian", 0x40e, "Latn")},
            {0x415, new LangScriptTagStruct("lidPolish", 0x415, "Latn")},
            {0x41f, new LangScriptTagStruct("lidTurkish", 0x41f, "Latn")},
            {0x429, new LangScriptTagStruct("lidFarsi", 0x429, "Arab")},
            {0x42d, new LangScriptTagStruct("lidBasque", 0x42d, "Latn")},
            {0x424, new LangScriptTagStruct("lidSlovenian", 0x424, "Latn")},
            {0x426, new LangScriptTagStruct("lidLatvian", 0x426, "Latn")},
            {0x427, new LangScriptTagStruct("lidLithuanian", 0x427, "Latn")},
            {0x418, new LangScriptTagStruct("lidRomanian", 0x418, "Latn")},
            {0x818, new LangScriptTagStruct("lidRomanianMoldavia", 0x818, "Latn")},
            {0x402, new LangScriptTagStruct("lidBulgarian", 0x402, "Cyrl")},
            {0x241a, new LangScriptTagStruct("lidSerbianLatin", 0x241a, "Latn")},
            {0x281a, new LangScriptTagStruct("lidSerbianCyrillic", 0x281a, "Cyrl")},
            {0x41a, new LangScriptTagStruct("lidCroatian", 0x41a, "Latn")},
            {0x491, new LangScriptTagStruct("lidGaelicScots", 0x491, "Latn")},
            {0x83c, new LangScriptTagStruct("lidGaelicIrish", 0x83c, "Latn")},
            {0x430, new LangScriptTagStruct("lidSutu", 0x430, "Latn")},
            {0x431, new LangScriptTagStruct("lidTsonga", 0x431, "Latn")},
            {0x432, new LangScriptTagStruct("lidTswana", 0x432, "Latn")},
            {0x433, new LangScriptTagStruct("lidVenda", 0x433, "Latn")},
            {0x434, new LangScriptTagStruct("lidXhosa", 0x434, "Latn")},
            {0x435, new LangScriptTagStruct("lidZulu", 0x435, "Latn")},
            {0x436, new LangScriptTagStruct("lidAfrikaans", 0x436, "Latn")},
            {0x412, new LangScriptTagStruct("lidKoreanExtWansung", 0x412, "Hang")},
            {0x422, new LangScriptTagStruct("lidUkranian", 0x422, "Cyrl")},
            {0x408, new LangScriptTagStruct("lidGreek", 0x408, "Grek")},
            {0x425, new LangScriptTagStruct("lidEstonian", 0x425, "Latn")},
            {0x456, new LangScriptTagStruct("lidGalician", 0x456, "Latn")},
            {0x401, new LangScriptTagStruct("lidArabic", 0x401, "Arab")},
            {0x40d, new LangScriptTagStruct("lidHebrew", 0x40d, "Hebr")},
            {0x411, new LangScriptTagStruct("lidJapanese", 0x411, "Jpan")},
            {0x41b, new LangScriptTagStruct("lidSlovak", 0x41b, "Latn")},
            {0x801, new LangScriptTagStruct("lidIraq", 0x801, "Arab")},
            {0xc01, new LangScriptTagStruct("lidEgyptian", 0xc01, "Arab")},
            {0x1001, new LangScriptTagStruct("lidLibya", 0x1001, "Arab")},
            {0x1401, new LangScriptTagStruct("lidAlgerian", 0x1401, "Arab")},
            {0x1801, new LangScriptTagStruct("lidMorocco", 0x1801, "Arab")},
            {0x1c01, new LangScriptTagStruct("lidTunisia", 0x1c01, "Arab")},
            {0x2001, new LangScriptTagStruct("lidOman", 0x2001, "Arab")},
            {0x2401, new LangScriptTagStruct("lidYemen", 0x2401, "Arab")},
            {0x2801, new LangScriptTagStruct("lidSyria", 0x2801, "Arab")},
            {0x2c01, new LangScriptTagStruct("lidJordan", 0x2c01, "Arab")},
            {0x3001, new LangScriptTagStruct("lidLebanon", 0x3001, "Arab")},
            {0x3401, new LangScriptTagStruct("lidKuwait", 0x3401, "Arab")},
            {0x3801, new LangScriptTagStruct("lidUAE", 0x3801, "Arab")},
            {0x3c01, new LangScriptTagStruct("lidBahrain", 0x3c01, "Arab")},
            {0x4001, new LangScriptTagStruct("lidQatar", 0x4001, "Arab")},
            {0x404, new LangScriptTagStruct("lidChineseTrad", 0x404, "Hant")},
            {0x804, new LangScriptTagStruct("lidChineseSimp", 0x804, "Hans")},
            {0xc04, new LangScriptTagStruct("lidHongkong", 0xc04, "Hant")},
            {0x1004, new LangScriptTagStruct("lidSingapore", 0x1004, "Hans")},
            {0x1404, new LangScriptTagStruct("lidMacau", 0x1404, "Hant")},
            {0x1409, new LangScriptTagStruct("lidEnglishNewZealand", 0x1409, "Latn")},
            {0x1809, new LangScriptTagStruct("lidEnglishIreland", 0x1809, "Latn")},
            {0x1c09, new LangScriptTagStruct("lidEnglishSouthAfrica", 0x1c09, "Latn")},
            {0x2009, new LangScriptTagStruct("lidEnglishJamaica", 0x2009, "Latn")},
            {0x2409, new LangScriptTagStruct("lidEnglishCaribbean", 0x2409, "Latn")},
            {0x2809, new LangScriptTagStruct("lidEnglishBelize", 0x2809, "Latn")},
            {0x2c09, new LangScriptTagStruct("lidEnglishTrinidad", 0x2c09, "Latn")},
            {0x3009, new LangScriptTagStruct("lidEnglishZimbabwe", 0x3009, "Latn")},
            {0x3409, new LangScriptTagStruct("lidEnglishPhilippines", 0x3409, "Latn")},
            {0x3809, new LangScriptTagStruct("lidEnglishIndonesia", 0x3809, "Latn")},
            {0x3c09, new LangScriptTagStruct("lidEnglishHongKong", 0x3c09, "Latn")},
            {0x4009, new LangScriptTagStruct("lidEnglishIndia", 0x4009, "Latn")},
            {0x4409, new LangScriptTagStruct("lidEnglishMalaysia", 0x4409, "Latn")},
            {0x4809, new LangScriptTagStruct("lidEnglishSingapore", 0x4809, "Latn")},
            {0x80a, new LangScriptTagStruct("lidSpanishMexican", 0x80a, "Latn")},
            //{0x80a, new LangScriptTagStruct("lidMexican", 0x80a, "Latn")},
            {0xc0a, new LangScriptTagStruct("lidSpanishModern", 0xc0a, "Latn")},
            {0x100a, new LangScriptTagStruct("lidGuatemala", 0x100a, "Latn")},
            {0x140a, new LangScriptTagStruct("lidCostaRica", 0x140a, "Latn")},
            {0x180a, new LangScriptTagStruct("lidPanama", 0x180a, "Latn")},
            {0x1c0a, new LangScriptTagStruct("lidDominicanRepublic", 0x1c0a, "Latn")},
            //{0x200a, new LangScriptTagStruct("lidSpanishSA", 0x200a, "Latn")},
            {0x200a, new LangScriptTagStruct("lidVenezuela", 0x200a, "Latn")},
            {0x240a, new LangScriptTagStruct("lidColombia", 0x240a, "Latn")},
            {0x280a, new LangScriptTagStruct("lidPeru", 0x280a, "Latn")},
            {0x2c0a, new LangScriptTagStruct("lidArgentina", 0x2c0a, "Latn")},
            {0x300a, new LangScriptTagStruct("lidEcuador", 0x300a, "Latn")},
            {0x340a, new LangScriptTagStruct("lidChile", 0x340a, "Latn")},
            {0x380a, new LangScriptTagStruct("lidUruguay", 0x380a, "Latn")},
            {0x3c0a, new LangScriptTagStruct("lidParguay", 0x3c0a, "Latn")},
            {0x400a, new LangScriptTagStruct("lidBolivia", 0x400a, "Latn")},
            {0x440a, new LangScriptTagStruct("lidElSalvador", 0x440a, "Latn")},
            {0x480a, new LangScriptTagStruct("lidHonduras", 0x480a, "Latn")},
            {0x4c0a, new LangScriptTagStruct("lidNicaragua", 0x4c0a, "Latn")},
            {0x500a, new LangScriptTagStruct("lidPuertoRico", 0x500a, "Latn")},
            {0x540a, new LangScriptTagStruct("lidSpanishUS", 0x540a, "Latn")},
            {0x80c, new LangScriptTagStruct("lidFrenchBelgian", 0x80c, "Latn")},
            {0x100c, new LangScriptTagStruct("lidFrenchSwiss", 0x100c, "Latn")},
            {0x140c, new LangScriptTagStruct("lidFrenchLuxembourg", 0x140c, "Latn")},
            {0x180c, new LangScriptTagStruct("lidFrenchMonaco", 0x180c, "Latn")},
            {0x1c0c, new LangScriptTagStruct("lidFrenchWestIndies", 0x1c0c, "Latn")},
            {0x200c, new LangScriptTagStruct("lidFrenchReunion", 0x200c, "Latn")},
            //{0x240c, new LangScriptTagStruct("lidFrenchCongoDRC", 0x240c, "Latn")},
            {0x240c, new LangScriptTagStruct("lidFrenchZaire", 0x240c, "Latn")},
            {0x280c, new LangScriptTagStruct("lidFrenchSenegal", 0x280c, "Latn")},
            {0x2c0c, new LangScriptTagStruct("lidFrenchCameroon", 0x2c0c, "Latn")},
            {0x300c, new LangScriptTagStruct("lidFrenchCotedIvoire", 0x300c, "Latn")},
            {0x340c, new LangScriptTagStruct("lidFrenchMali", 0x340c, "Latn")},
            {0x3c0c, new LangScriptTagStruct("lidFrenchHaiti", 0x3c0c, "Latn")},
            {0x380c, new LangScriptTagStruct("lidFrenchMorocco", 0x380c, "Latn")},
            {0x40f, new LangScriptTagStruct("lidIcelandic", 0x40f, "Latn")},
            {0x810, new LangScriptTagStruct("lidItalianSwiss", 0x810, "Latn")},
            //{0x417, new LangScriptTagStruct("lidRhaetoRomanic", 0x417, "Latn")},
            {0x417, new LangScriptTagStruct("lidRomanic", 0x417, "Latn")},
            {0x819, new LangScriptTagStruct("lidRussianMoldavia", 0x819, "Cyrl")},
            //{0x41a, new LangScriptTagStruct("lidCroat", 0x41a, "Latn")},
            {0x81a, new LangScriptTagStruct("lidSerbianLatinSerbMont", 0x81a, "Latn")},
            {0xc1a, new LangScriptTagStruct("lidSerbianCyrillicSerbMont", 0xc1a, "Cyrl")},
            //{0x81a, new LangScriptTagStruct("lidCroatSerbo", 0x81a, "Latn")},
            {0x101a, new LangScriptTagStruct("lidBosniaHerzegovina", 0x101a, "Latn")},
            {0x141a, new LangScriptTagStruct("lidBosnianBosniaHerzegovinaLatin", 0x141a, "Latn")},
            {0x181a, new LangScriptTagStruct("lidSerbianBosniaHerzegovinaLatin", 0x181a, "Latn")},
            {0x1c1a, new LangScriptTagStruct("lidSerbianBosniaHerzegovinaCyrillic", 0x1c1a, "Cyrl")},
            {0x201a, new LangScriptTagStruct("lidBosnianBosniaHerzegovinaCyrillic", 0x201a, "Cyrl")},
            {0x2c1a, new LangScriptTagStruct("lidSerbianMontenegroLatin", 0x2c1a, "Latn")},
            {0x301a, new LangScriptTagStruct("lidSerbianMontenegroCyrillic", 0x301a, "Cyrl")},
            {0x41c, new LangScriptTagStruct("lidAlbanian", 0x41c, "Latn")},
            {0x81d, new LangScriptTagStruct("lidSwedishFinland", 0x81d, "Latn")},
            {0x41e, new LangScriptTagStruct("lidThai", 0x41e, "Thai")},
            {0x420, new LangScriptTagStruct("lidUrdu", 0x420, "Arab")},
            //{0x421, new LangScriptTagStruct("lidBahasa", 0x421, "Latn")},
            {0x421, new LangScriptTagStruct("lidIndonesian", 0x421, "Latn")},
            {0x423, new LangScriptTagStruct("lidByelorussian", 0x423, "Cyrl")},
            {0x428, new LangScriptTagStruct("lidTajik", 0x428, "Cyrl")},
            {0x42a, new LangScriptTagStruct("lidVietnamese", 0x42a, "Viet")},
            {0x42b, new LangScriptTagStruct("lidArmenian", 0x42b, "Armn")},
            {0x42c, new LangScriptTagStruct("lidAzeriLatin", 0x42c, "Latn")},
            {0x82c, new LangScriptTagStruct("lidAzeriCyrillic", 0x82c, "Cyrl")},
            {0x42e, new LangScriptTagStruct("lidSorbian", 0x42e, "Latn")},
            {0x82e, new LangScriptTagStruct("lidLowerSorbian", 0x82e, "Latn")},
            {0x42f, new LangScriptTagStruct("lidMacedonian", 0x42f, "Cyrl")},
            {0x437, new LangScriptTagStruct("lidGeorgian", 0x437, "Geor")},
            {0x438, new LangScriptTagStruct("lidFaeroese", 0x438, "Latn")},
            {0x439, new LangScriptTagStruct("lidHindi", 0x439, "Deva")},
            {0x43a, new LangScriptTagStruct("lidMaltese", 0x43a, "Latn")},
            {0x43b, new LangScriptTagStruct("lidSamiLappish", 0x43b, "Latn")},
            {0x83b, new LangScriptTagStruct("lidNorthSamiSwe", 0x83b, "Latn")},
            {0xc3b, new LangScriptTagStruct("lidNorthernSamiFi", 0xc3b, "Latn")},
            {0x103b, new LangScriptTagStruct("lidLuleSamiNor", 0x103b, "Latn")},
            {0x143b, new LangScriptTagStruct("lidLuleSamiSwe", 0x143b, "Latn")},
            {0x183b, new LangScriptTagStruct("lidSouthSamiNor", 0x183b, "Latn")},
            {0x1c3b, new LangScriptTagStruct("lidSouthSamiSwe", 0x1c3b, "Latn")},
            {0x203b, new LangScriptTagStruct("lidSkoltSami", 0x203b, "Latn")},
            {0x243b, new LangScriptTagStruct("lidInariSami", 0x243b, "Latn")},
            {0x43d, new LangScriptTagStruct("lidYiddish", 0x43d, "Hebr")},
            {0x43e, new LangScriptTagStruct("lidMalaysian", 0x43e, "Latn")},
            {0x83e, new LangScriptTagStruct("lidMalayBrunei", 0x83e, "Latn")},
            {0x43f, new LangScriptTagStruct("lidKazakh", 0x43f, "Cyrl")},
            {0x440, new LangScriptTagStruct("lidKyrgyz", 0x440, "Cyrl")},
            {0x441, new LangScriptTagStruct("lidSwahili", 0x441, "Latn")},
            {0x442, new LangScriptTagStruct("lidTurkmen", 0x442, "Latn")},
            {0x443, new LangScriptTagStruct("lidUzbekLatin", 0x443, "Latn")},
            {0x843, new LangScriptTagStruct("lidUzbekCyrillic", 0x843, "Cyrl")},
            {0x444, new LangScriptTagStruct("lidTatar", 0x444, "Cyrl")},
            {0x445, new LangScriptTagStruct("lidBengali", 0x445, "Beng")},
            {0x845, new LangScriptTagStruct("lidBengaliBangladesh", 0x845, "Beng")},
            {0x446, new LangScriptTagStruct("lidPunjabi", 0x446, "Guru")},
            {0x846, new LangScriptTagStruct("lidPunjabiPakistan", 0x846, "Arab")},
            {0x447, new LangScriptTagStruct("lidGujarati", 0x447, "Gujr")},
            {0x448, new LangScriptTagStruct("lidOriya", 0x448, "Orya")},
            {0x449, new LangScriptTagStruct("lidTamil", 0x449, "Taml")},
            {0x44a, new LangScriptTagStruct("lidTelugu", 0x44a, "Telu")},
            {0x44b, new LangScriptTagStruct("lidKannada", 0x44b, "Knda")},
            {0x44c, new LangScriptTagStruct("lidMalayalam", 0x44c, "Mlym")},
            {0x44d, new LangScriptTagStruct("lidAssamese", 0x44d, "Beng")},
            {0x44e, new LangScriptTagStruct("lidMarathi", 0x44e, "Deva")},
            {0x44f, new LangScriptTagStruct("lidSanskrit", 0x44f, "Deva")},
            {0x450, new LangScriptTagStruct("lidMongolian", 0x450, "Cyrl")},
            {0x850, new LangScriptTagStruct("lidMongolianMongo", 0x850, "Mong")},
            {0x451, new LangScriptTagStruct("lidTibetan", 0x451, "Tibt")},
            {0x851, new LangScriptTagStruct("lidBhutanese", 0x851, "Tibt")},
            {0x452, new LangScriptTagStruct("lidWelsh", 0x452, "Latn")},
            {0x453, new LangScriptTagStruct("lidKhmer", 0x453, "Khmr")},
            {0x454, new LangScriptTagStruct("lidLao", 0x454, "Laoo")},
            {0x455, new LangScriptTagStruct("lidBurmese", 0x455, "Mymr")},
            {0x457, new LangScriptTagStruct("lidKonkani", 0x457, "Deva")},
            {0x458, new LangScriptTagStruct("lidManipuri", 0x458, "Beng")},
            {0x459, new LangScriptTagStruct("lidSindhi", 0x459, "Deva")},
            {0x859, new LangScriptTagStruct("lidSindhiPakistan", 0x859, "Arab")},
            {0x45a, new LangScriptTagStruct("lidSyriac", 0x45a, "Syrc")},
            {0x45b, new LangScriptTagStruct("lidSinhalese", 0x45b, "Sinh")},
            {0x45c, new LangScriptTagStruct("lidCherokee", 0x45c, "Cher")},
            {0x45d, new LangScriptTagStruct("lidInuktitut", 0x45d, "Cans")},
            {0x85d, new LangScriptTagStruct("lidInuktitutLatin", 0x85d, "Latn")},
            {0x45e, new LangScriptTagStruct("lidAmharic", 0x45e, "Ethi")},
            {0x45f, new LangScriptTagStruct("lidTamazight", 0x45f, "Arab")},
            {0x85f, new LangScriptTagStruct("lidTamazightLatin", 0x85f, "Latn")},
            {0x460, new LangScriptTagStruct("lidKashmiri", 0x460, "Arab")},
            {0x860, new LangScriptTagStruct("lidKashmiriIndia", 0x860, "Deva")},
            {0x461, new LangScriptTagStruct("lidNepali", 0x461, "Deva")},
            {0x861, new LangScriptTagStruct("lidNepaliIndia", 0x861, "Deva")},
            {0x462, new LangScriptTagStruct("lidFrisian", 0x462, "Latn")},
            {0x463, new LangScriptTagStruct("lidPashto", 0x463, "Arab")},
            {0x464, new LangScriptTagStruct("lidFilipino", 0x464, "Latn")},
            {0x465, new LangScriptTagStruct("lidMaldivian", 0x465, "Thaa")},
            {0x466, new LangScriptTagStruct("lidEdo", 0x466, "Latn")},
            {0x467, new LangScriptTagStruct("lidFulfulde", 0x467, "Latn")},
            {0x468, new LangScriptTagStruct("lidHausa", 0x468, "Latn")},
            {0x469, new LangScriptTagStruct("lidIbibio", 0x469, "Latn")},
            {0x46a, new LangScriptTagStruct("lidYoruba", 0x46a, "Latn")},
            {0x46b, new LangScriptTagStruct("lidQuechuaBol", 0x46b, "Latn")},
            {0x86b, new LangScriptTagStruct("lidQuechuaEcu", 0x86b, "Latn")},
            {0xc6b, new LangScriptTagStruct("lidQuechuaPe", 0xc6b, "Latn")},
            {0x46c, new LangScriptTagStruct("lidSesothoSaLeboa", 0x46c, "Latn")},
            {0x46d, new LangScriptTagStruct("lidBashkir", 0x46d, "Cyrl")},
            {0x46e, new LangScriptTagStruct("lidLuxembourgish", 0x46e, "Latn")},
            {0x46f, new LangScriptTagStruct("lidGreenlandic", 0x46f, "Latn")},
            {0x470, new LangScriptTagStruct("lidIgbo", 0x470, "Latn")},
            {0x471, new LangScriptTagStruct("lidKanuri", 0x471, "Latn")},
            {0x472, new LangScriptTagStruct("lidOromo", 0x472, "Latn")},
            {0x473, new LangScriptTagStruct("lidTigrignaEthiopic", 0x473, "Ethi")},
            {0x873, new LangScriptTagStruct("lidTigrignaEritrea", 0x873, "Ethi")},
            {0x474, new LangScriptTagStruct("lidGuarani", 0x474, "Latn")},
            {0x475, new LangScriptTagStruct("lidHawaiian", 0x475, "Latn")},
            {0x476, new LangScriptTagStruct("lidLatin", 0x476, "Latn")},
            {0x477, new LangScriptTagStruct("lidSomali", 0x477, "Latn")},
            {0x478, new LangScriptTagStruct("lidYi", 0x478, "Yiii")},
            {0x47a, new LangScriptTagStruct("lidMapudungun", 0x47a, "Latn")},
            {0x47c, new LangScriptTagStruct("lidMohawk", 0x47c, "Latn")},
            {0x47e, new LangScriptTagStruct("lidBreton", 0x47e, "Latn")},
            {0x480, new LangScriptTagStruct("lidUighur", 0x480, "Uigh")},
            {0x481, new LangScriptTagStruct("lidMaori", 0x481, "Latn")},
            {0x482, new LangScriptTagStruct("lidOccitan", 0x482, "Latn")},
            {0x483, new LangScriptTagStruct("lidCorsican", 0x483, "Latn")},
            {0x484, new LangScriptTagStruct("lidAlsatian", 0x484, "Latn")},
            {0x485, new LangScriptTagStruct("lidSakha", 0x485, "Cyrl")},
            {0x486, new LangScriptTagStruct("lidKiche", 0x486, "Latn")},
            {0x487, new LangScriptTagStruct("lidKinyarwanda", 0x487, "Latn")},
            {0x488, new LangScriptTagStruct("lidWolof", 0x488, "Latn")},
            {0x48c, new LangScriptTagStruct("lidDari", 0x48c, "Arab")},
        };

        /// <summary>
        /// Get script tag (e.g. Hant) by LCID (e.g. 0x404).
        /// </summary>
        /// <param name="lcid">LCID (e.g. 0x404).</param>
        /// <returns>Return script tag if found, otherwise return null.</returns>
        public static String GetScriptTagByLCID(int lcid)
        {
            return (LangScriptTags.ContainsKey(lcid)) ? LangScriptTags[lcid].ScriptTag : null;
        }

        /// <summary>
        /// Get script tag (e.g. Hant) by locale (e.g. zh-TW).
        /// </summary>
        /// <param name="locale">Locale (e.g. zh-TW).</param>
        /// <returns>Return script tag if found, otherwise return null.</returns>
        public static String GetScriptTagByLocale(String locale)
        {
            return GetScriptTagByLCID(new CultureInfo(locale, false).LCID);
        }
    }
}
